/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_adambruce_jcpuid_bridge_CpuidBridgeImpl */

#ifndef _Included_net_adambruce_jcpuid_bridge_CpuidBridgeImpl
#define _Included_net_adambruce_jcpuid_bridge_CpuidBridgeImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_adambruce_jcpuid_bridge_CpuidBridgeImpl
 * Method:    executeCPUIDNative
 * Signature: (I)Lnet/adambruce/jcpuid/type/CpuidResult;
 */
JNIEXPORT jobject JNICALL Java_net_adambruce_jcpuid_bridge_CpuidBridgeImpl_executeCPUIDNative__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_adambruce_jcpuid_bridge_CpuidBridgeImpl
 * Method:    executeCPUIDNative
 * Signature: (II)Lnet/adambruce/jcpuid/type/CpuidResult;
 */
JNIEXPORT jobject JNICALL Java_net_adambruce_jcpuid_bridge_CpuidBridgeImpl_executeCPUIDNative__II
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
