/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_adambruce_jcpuid_bridge_DefaultCPUIDBridge */

#ifndef _Included_net_adambruce_jcpuid_bridge_DefaultCPUIDBridge
#define _Included_net_adambruce_jcpuid_bridge_DefaultCPUIDBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_adambruce_jcpuid_bridge_DefaultCPUIDBridge
 * Method:    executeCPUIDNative
 * Signature: (I)Lnet/adambruce/jcpuid/type/Result;
 */
JNIEXPORT jobject JNICALL Java_net_adambruce_jcpuid_bridge_DefaultCPUIDBridge_executeCPUIDNative__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_adambruce_jcpuid_bridge_DefaultCPUIDBridge
 * Method:    executeCPUIDNative
 * Signature: (II)Lnet/adambruce/jcpuid/type/Result;
 */
JNIEXPORT jobject JNICALL Java_net_adambruce_jcpuid_bridge_DefaultCPUIDBridge_executeCPUIDNative__II
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
