name: build-jcpuid
on: [push]

jobs:
  build-jcpuid-native-linux:
    name: Build linux native library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      - run: mvn clean package -f jcpuid-native/jcpuid-native-linux/
      - run: mvn deploy -f jcpuid-native/jcpuid-native-linux/
        env:
          GITHUB_TOKEN: ${{ github.token }}

  build-jcpuid-native-windows:
    name: Build windows native library
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      - run: mvn clean package -f jcpuid-native/jcpuid-native-windows/
      - run: mvn deploy -f jcpuid-native/jcpuid-native-windows/
        env:
          GITHUB_TOKEN: ${{ github.token }}


  build-jcpuid-native-macos:
    name: Build macos native library
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      - run: mvn clean package -f jcpuid-native/jcpuid-native-macos/
      - run: mvn deploy -f jcpuid-native/jcpuid-native-macos/
        env:
          GITHUB_TOKEN: ${{ github.token }}

  build-jcpuid-jar:
    name: Build and package JAR
    runs-on: ubuntu-latest
    needs:
      - build-jcpuid-native-linux
      - build-jcpuid-native-windows
      - build-jcpuid-native-macos
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      - run: mvn clean package -f jcpuid-lib
