name: build-jcpuid
on: [push]

jobs:
  build-all-platforms:
    name: Build native libs
    strategy:
      matrix:
        platform:
          - name: ubuntu-latest
            lib: linux
          - name: windows-latest
            lib: windows
          - name: macos-13
            lib: macos
    runs-on: ${{ matrix.platform.name }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      - run: mvn deploy -f jcpuid-native/jcpuid-native-${{ matrix.platform.lib }} -Pnative-${{ matrix.platform.lib }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

  build-jcpuid-jar:
    name: Build Shaded Jar
    runs-on: ubuntu-latest
    needs:
      - build-all-platforms
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      - run: mvn clean package
