name: build-jcpuid
on: [push]

env:
  JAVA_HOME: "$JAVA_HOME_8_amd64"

jobs:
  build-jcpuid-native-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      - run: mvn clean package -f jcpuid-native/jcpuid-native-linux/
      - run: ls jcpuid-native/jcpuid-native-linux/target

  build-jcpuid-native-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      - run: mvn clean package -f jcpuid-native/jcpuid-native-windows/ -X
      - run: ls jcpuid-native/jcpuid-native-windows/target
#
#  build-jcpuid-native-macos:
#    runs-on: macos-13
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: '8'
#      - run: mvn clean package -f jcpuid-native/jcpuid-native-macos/