name: Build
on: push

jobs:
  # Build the java code first, since this is most likely to fail.
  # We run this in the project root to ensure everything gets built (except the
  # native libs)
  build-jcpuid-jars:
    name: Build Jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      - run: mvn clean install
        env:
          GITHUB_TOKEN: ${{ github.token }}

  build-all-platforms:
    needs: build-jcpuid-jars
    name: Build native libs
    strategy:
      matrix:
        platform:
          - name: ubuntu-latest
            lib: linux
          - name: windows-latest
            lib: windows
          - name: macos-13
            lib: macos
    runs-on: ${{ matrix.platform.name }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      - run: mvn clean install -f jcpuid-native/jcpuid-native-${{ matrix.platform.lib }} -Pnative-${{ matrix.platform.lib }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
