name: build-jcpuid
on: [push]

jobs:
  build-jcpuid-native-linux:
    name: Build linux native library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      - run: mvn clean package -f jcpuid-native/jcpuid-native-linux/
      - uses: actions/upload-artifact@v4
        with:
          name: 'jcpuid-native-linux-1.0-SNAPSHOT-amd64-Linux-gpp-shared.nar'
          path: 'jcpuid-native/jcpuid-native-linux/target/jcpuid-native-linux-1.0-SNAPSHOT-amd64-Linux-gpp-shared.nar'
          if-no-files-found: 'error'

  build-jcpuid-native-windows:
    name: Build windows native library
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      - run: mvn clean package -f jcpuid-native/jcpuid-native-windows/
      - uses: actions/upload-artifact@v4
        with:
          name: 'jcpuid-native-windows-1.0-SNAPSHOT-amd64-Windows-gcc-shared.nar'
          path: 'jcpuid-native/jcpuid-native-windows/target/jcpuid-native-windows-1.0-SNAPSHOT-amd64-Windows-gcc-shared.nar'
          if-no-files-found: 'error'


  build-jcpuid-native-macos:
    name: Build macos native library
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      - run: mvn clean package -f jcpuid-native/jcpuid-native-macos/
      - uses: actions/upload-artifact@v4
        with:
          name: 'jcpuid-native-macos-1.0-SNAPSHOT-x86_64-MacOSX-gpp-shared.nar'
          path: 'jcpuid-native/jcpuid-native-macos/target/jcpuid-native-macos-1.0-SNAPSHOT-x86_64-MacOSX-gpp-jni.nar'
          if-no-files-found: 'error'

  build-jcpuid-jar:
    name: Build and package JAR
    runs-on: ubuntu-latest
    needs:
      - build-jcpuid-native-linux
      - build-jcpuid-native-windows
      - build-jcpuid-native-macos
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      - uses: actions/download-artifact@v4
        with:
          name: 'jcpuid-native-linux-1.0-SNAPSHOT-amd64-Linux-gpp-shared.nar'
          path: jcpuid-native/jcpuid-native-linux/target/
      - uses: actions/download-artifact@v4
        with:
          name: 'jcpuid-native-windows-1.0-SNAPSHOT-amd64-Windows-gcc-shared.nar'
          path: jcpuid-native/jcpuid-native-windows/target/
      - uses: actions/download-artifact@v4
        with:
          name: 'jcpuid-native-macos-1.0-SNAPSHOT-x86_64-MacOSX-gpp-jni.nar'
          path: jcpuid-native/jcpuid-native-macos/target/


  cleanup:
    name: Cleanup artifacts
    runs-on: ubuntu-latest
    needs:
      - build-jcpuid-jar
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: jcpuid-native-*.nar
