name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build-all-platforms:
    name: Build and deploy native libs
    strategy:
      matrix:
        platform:
          - name: ubuntu-latest
            lib: linux
          - name: windows-latest
            lib: windows
          - name: macos-13
            lib: macos
    runs-on: ${{ matrix.platform.name }}
    steps:
      - name: Remove tag prefix
        shell: bash
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Set pom.xml version for this release
        run: mvn -B versions:set -DnewVersion=$VERSION -DgenerateBackupPoms=false
      - run: mvn -B deploy -f jcpuid-native/jcpuid-native-${{ matrix.platform.lib }} -Pnative-${{ matrix.platform.lib }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

  build-jcpuid-jar:
    name: Build and deploy Jar
    runs-on: ubuntu-latest
    needs: build-all-platforms
    steps:
      - name: Remove tag prefix
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Set pom.xml version for this release
        run: mvn -B versions:set -DnewVersion=$VERSION -DgenerateBackupPoms=false
      - run: mvn -B deploy -f jcpuid-lib
        env:
          GITHUB_TOKEN: ${{ github.token }}

  bump-pom-version-snapshot:
    name: Bump POMs for snapshot
    runs-on: ubuntu-latest
    needs: build-jcpuid-jar
    steps:
      - name: Remove tag prefix
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Set pom.xml version for this release
        run: mvn -B versions:set -DnewVersion=$VERSION -DgenerateBackupPoms=false
      - name: Set pom.xml snapshot version
        run: mvn -B versions:set -DnextSnapshot=true -DgenerateBackupPoms=false
      - uses: EndBug/add-and-commit@v9
        with:
          message: Bump POM versions for snapshot
          new_branch: main
          push: true